siteTitle = "Vojtěch Mikšů"
siteAuthor = "Vojtěch Mikšů"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/vmiksu"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = "UA-31410016-1"

linkPrefix = ""
noProductionJavascript = true
